// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@v0.17.0',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/ploigos/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowEverything(
    stepRunnerConfigDir: 'cicd/ploigos-step-runner-config/',
    pgpKeysSecretName: 'tssc-gpg-key',

    workflowWorkersImagePullPolicy: 'Always',

    workflowServiceAccountName: 'jenkins',

    workflowWorkerImageDefault: 'quay.io/ploigos/ploigos-ci-agent-jenkins:nightly',
    workflowWorkerImageUnitTest: 'quay.io/ploigos/ploigos-tool-maven:nightly',
    workflowWorkerImagePackage: 'quay.io/ploigos/ploigos-tool-maven:nightly',
    workflowWorkerImageStaticCodeAnalysis: 'quay.io/ploigos/ploigos-tool-sonar:nightly',
    workflowWorkerImagePushArtifacts: 'quay.io/ploigos/ploigos-tool-maven:nightly',
    workflowWorkerImageContainerOperations: 'quay.io/ploigos/ploigos-tool-containers:nightly',
    workflowWorkerImageContainerImageStaticComplianceScan: 'quay.io/ploigos/ploigos-tool-openscap:nightly',
    workflowWorkerImageContainerImageStaticVulnerabilityScan: 'quay.io/ploigos/ploigos-tool-openscap:nightly',
    workflowWorkerImageDeploy: 'quay.io/agoossen/ploigos-tool-argocd:nightly',
    workflowWorkerImageValidateEnvironmentConfiguration: 'quay.io/ploigos/ploigos-tool-config-lint:nightly',
    workflowWorkerImageUAT: 'quay.io/ploigos/ploigos-tool-maven:nightly',
    
    separatePlatformConfig: false
)
